import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { BrowserRouter } from 'react-router-dom';
import {Route,Routes}  from 'react-router-dom';
import Header from "../components/header.js";
import HeroSection from "../components/heroSection.js";
import SearchComp from "../components/search.js";
import QRScanner from "@/components/qrscanner.js";

export default function Home() {
  return (
    <>
    {/* <BrowserRouter> */}
      <Head>
        <title>Etherscan Search</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>      </Head>
        <h1 className="title">
</h1>
      <section className={styles.main}>
        <Header/>
        <SearchComp />
        <HeroSection />
      {/* <QRScanner/> */}
      </section>
      {/* <Routes>
      <Route exact path="/QRScanner" element={<QRScanner/>} ></Route>
      </Routes> */}
      {/* </BrowserRouter> */}
        

    </>
  );
}